### Matching Algorithm Integration

In [ ]:
import json
import pandas as pd
with open("subset_20percent_translated_final.json", "r", encoding="utf-8") as f:
    data = json.load(f)

courses = data["events"]["event"]
df = pd.json_normalize(courses)
df.head()

,guid,number,last_name,subtitle,district,event_type,minimum_participants,current_participants,maximum_participants,number_of_sessions,...,locations.address.city,locations.address.street,locations.address.room,locations.address.longitude,locations.address.latitude,locations.address.accessible,locations.appointments.weekday,locations.appointments.start_date,locations.appointments.start_time,locations.appointments.end_time
0,604369,FK3.840,Body Percussion – the Rhythmic Sound of the Body,None,Friedrichshain-Kreuzberg,Course,8,0,10,10,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,610723,FK4.D-ik-179-5a,Deutsch B1.1,Aufbaumodul 5,Friedrichshain-Kreuzberg,Course,12,1,20,100,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,656403,SZ810-29-04-01,Deutsch Integrationskurs A1.1,Basissprachkurs Modul 1,Steglitz-Zehlendorf,Course,8,6,12,100,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,658796,Mi404-B192S-13,Deutsch Orientierungskurs,None,Mitte,Course,8,5,16,100,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,683442,Sp4.224.W9,Deutsch Alphabetisierung W9,Deutsch Alphabetisierung-Integrationskurs,Spandau,Course,10,1,16,100,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [20]:
df.columns

Index(['guid', 'number', 'last_name', 'subtitle', 'district', 'event_type',
       'minimum_participants', 'current_participants', 'maximum_participants',
       'number_of_sessions', 'start_date', 'end_date', 'target_group',
       'keywords', 'text', 'category.@version', 'category.#text',
       'registration.phone', 'registration.email', 'registration.link',
       'contact_person.salutation', 'contact_person.title',
       'contact_person.last_name', 'contact_person.first_name',
       'contact_person.phone', 'contact_person.email', 'locations.address',
       'locations.appointments', 'price.amount', 'price.discount_possible',
       'price.additional', 'lecturer.salutation', 'lecturer.title',
       'lecturer.last_name', 'lecturer.first_name', 'website.type',
       'website.last_name', 'website.uri', 'lecturer',
       'merkmale.merkmal.last_name', 'merkmale.merkmal.wert',
       'locations.address.facility', 'locations.address.postal_code',
       'locations.address.city', 'locations.address.street',
       'locations.address.room', 'locations.address.longitude',
       'locations.address.latitude', 'locations.address.accessible',
       'locations.appointments.weekday', 'locations.appointments.start_date',
       'locations.appointments.start_time', 'locations.appointments.end_time'],
      dtype='object')

In [21]:
df.columns = (
    df.columns
    .str.lower()
    .str.replace('.', '_', regex=False)
    .str.replace('@', '', regex=False)
    .str.replace('#', '', regex=False)
)

df.head()

,guid,number,last_name,subtitle,district,event_type,minimum_participants,current_participants,maximum_participants,number_of_sessions,...,locations_address_city,locations_address_street,locations_address_room,locations_address_longitude,locations_address_latitude,locations_address_accessible,locations_appointments_weekday,locations_appointments_start_date,locations_appointments_start_time,locations_appointments_end_time
0,604369,FK3.840,Body Percussion – the Rhythmic Sound of the Body,None,Friedrichshain-Kreuzberg,Course,8,0,10,10,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,610723,FK4.D-ik-179-5a,Deutsch B1.1,Aufbaumodul 5,Friedrichshain-Kreuzberg,Course,12,1,20,100,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,656403,SZ810-29-04-01,Deutsch Integrationskurs A1.1,Basissprachkurs Modul 1,Steglitz-Zehlendorf,Course,8,6,12,100,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,658796,Mi404-B192S-13,Deutsch Orientierungskurs,None,Mitte,Course,8,5,16,100,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,683442,Sp4.224.W9,Deutsch Alphabetisierung W9,Deutsch Alphabetisierung-Integrationskurs,Spandau,Course,10,1,16,100,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [26]:
df['category_text'].value_counts()

category_text
3.02    266
3.01    215
4.04    177
2.07     88
4.22     87
4.06     74
5.01     73
2.11     62
5.06     57
2.09     46
4.09     43
3.05     40
4.08     34
2.08     32
5.07     25
1.06     24
2.05     23
4.24     22
4.15     21
5.03     19
2.02     19
4.01     19
5.00     18
2.13     14
4.02     14
2.10     13
4.20     11
1.01     11
5.02     10
2.04     10
4.26     10
3.03     10
1.04      8
2.00      7
2.06      7
3.06      6
4.10      5
5.08      5
5.04      5
4.14      5
1.08      4
1.02      4
1.03      4
7.00      4
1.09      4
3.00      4
4.00      3
4.19      3
1.11      3
3.04      3
7.04      2
5.05      2
4.17      1
1.00      1
2.01      1
4.16      1
1.07      1
2.12      1
Name: count, dtype: int64

In [28]:
category_map = {
    '1.06': 'Basic Education and Literacy',
    '2.05': 'Society and Environment',
    '2.07': 'History and Politics',
    '2.08': 'Philosophy and Ethics',
    '2.09': 'Law and Justice',
    '2.11': 'Intercultural Learning',
    '3.01': 'Health and Wellbeing',
    '3.02': 'Movement and Body Awareness',
    '3.05': 'Nutrition and Cooking',
    '4.04': 'Foreign Languages',
    '4.06': 'German as a Second Language',
    '4.08': 'Integration Courses',
    '4.09': 'Literature and Writing',
    '4.15': 'Music and Voice',
    '4.22': 'Art and Creativity',
    '4.24': 'Photography and Film',
    '5.01': 'Digital Basics',
    '5.06': 'Media Skills',
    '5.07': 'Programming and Data'
}
df['category_label'] = df['category_text'].map(category_map)

df['category_label'].value_counts()

category_label
Movement and Body Awareness     266
Health and Wellbeing            215
Foreign Languages               177
History and Politics             88
Art and Creativity               87
German as a Second Language      74
Digital Basics                   73
Intercultural Learning           62
Media Skills                     57
Law and Justice                  46
Literature and Writing           43
Nutrition and Cooking            40
Integration Courses              34
Philosophy and Ethics            32
Programming and Data             25
Basic Education and Literacy     24
Society and Environment          23
Photography and Film             22
Music and Voice                  21
Name: count, dtype: int64

In [35]:
df.to_csv("subset_20percent_translated_final.csv", index=False)

In [ ]:
import pandas as pd
import numpy as np

# define levenshtein similarity function
def levenshtein(a, b, ratio=True, lowercase=True):
    # optional: convert both strings to lowercase
    if lowercase:
        a = a.lower()
        b = b.lower()

    # if one string is empty, distance = length of the other
    if a == '':
        return len(b)
    if b == '':
        return len(a)

    # initialize matrix of size (len(a)+1) x (len(b)+1)
    n, m = len(a), len(b)
    lev = np.zeros((n + 1, m + 1))

    # fill in the first column and row
    for i in range(n + 1):
        lev[i][0] = i
    for j in range(m + 1):
        lev[0][j] = j

    # fill in the matrix based on insertion, deletion, substitution
    for i in range(1, n + 1):
        for j in range(1, m + 1):
            cost = 0 if a[i - 1] == b[j - 1] else 1
            lev[i][j] = min(
                lev[i - 1][j] + 1,        # deletion
                lev[i][j - 1] + 1,        # insertion
                lev[i - 1][j - 1] + cost  # substitution
            )

    # return similarity score (higher = better match)
    return (n + m - lev[n][m]) / (n + m) if ratio else lev[n][m]

# define the top-matching function
def get_top_matches(df, user_input, location=None, top_n=5):
    # optionally filter by district if location is provided
    if location:
        df = df[df['district'].str.lower() == location.lower()]

    # create a copy so we don’t change the original dataframe
    df = df.copy()

    # apply the similarity function to the 'last_name' (title) of each course
    df['similarity'] = df['last_name'].apply(
        lambda x: levenshtein(user_input, str(x), ratio=True)
    )

    # return the top N results, sorted by similarity score
    return df.sort_values(by='similarity', ascending=False).head(top_n)

In [39]:
user_query = "social science"
user_location = "Mitte"

# get best matches
top_results = get_top_matches(df, user_query, user_location, top_n=10)

# display results
print(top_results[['last_name', 'district', 'similarity']])

                                     last_name district  similarity
853                          Modern Jazz Dance    Mitte    0.621622
844                       Stepptanz Aufbaukurs    Mitte    0.621622
861           Tango Argentino - Kurs für Paare    Mitte    0.621622
860  Salsa Cubana - Salsa Cross Body - Bachata    Mitte    0.621622
859                                  Tanzlabor    Mitte    0.621622
858                  Modern Dance - Aufbaukurs    Mitte    0.621622
857            Zeitgenössischer Ausdruckstanz     Mitte    0.621622
855                   Ballett for Everybody II    Mitte    0.621622
854                    Ballett for Everybody I    Mitte    0.621622
843                  Bollywood-Tanz - Workshop    Mitte    0.621622

In [40]:
user_query = "ai"
user_location = "Mitte"

# get best matches
top_results = get_top_matches(df, user_query, user_location, top_n=5)

# display results
print(top_results[['last_name', 'district', 'similarity']])

                                            last_name district  similarity
583                 Einführung in die Meisner-Technik    Mitte         0.6
639                      Galeriewelten Berlins Teil 2    Mitte         0.6
630                                Sachbuch schreiben    Mitte         0.6
629                Lyrikworkshop - Stadtverdichtungen    Mitte         0.6
628  Sommerwerkstatt Genre: Das Geheimnis der Fantasy    Mitte         0.6

In [41]:
user_query = "ai"
user_location = "Mitte"

# get best matches
top_results = get_top_matches(df, user_query, user_location, top_n=5)

# display results
print(top_results[['last_name', 'district', 'similarity']])

                                            last_name district  similarity
583                 Einführung in die Meisner-Technik    Mitte         0.6
639                      Galeriewelten Berlins Teil 2    Mitte         0.6
630                                Sachbuch schreiben    Mitte         0.6
629                Lyrikworkshop - Stadtverdichtungen    Mitte         0.6
628  Sommerwerkstatt Genre: Das Geheimnis der Fantasy    Mitte         0.6


The algorithm measures how similar two pieces of text are by counting how many small edits it would take to turn one into the other. 

These edits can be:
1. Changing one letter (like changing a to e)
2. Removing a letter
3. Adding a letter

The fewer edits needed, the more similar the two words are.

- Match - Same character, same position - 0 cost

- Substitution - Different character, same position - 1 cost

- Insertion - One string has an extra character - 1 cost

- Deletion - One string lacks a character - 1 cost